import { Integration, Spec } from "./Spec";

export const Ours: Spec = {
    id: 'purecore',
    name: 'purecore.io',
    url: "http://purecore.io/",
    developerTooling: Integration.YES,
    monetization: {
        worldwidePaymentsProcessing: Integration.YES,
        instantActions: Integration.YES,
        unlimitedPackages: Integration.YES,
        recurringPayments: Integration.YES,
        multipleServerSupport: Integration.YES,
        multipleGameSupport: Integration.YES,
        discordSupport: Integration.YES,
        sales: Integration.YES_PAID,
        coupons: Integration.YES,
        giftcards: Integration.YES_PAID,
        abandonedBasketRecovery: Integration.YES_PAID,
        purchaseFollowups: Integration.YES_PAID,
        metadataDrivenDiscounts: Integration.YES,
        giftingOptions: Integration.YES,
        upselling: Integration.YES_PAID,
        unifiedPayments: Integration.YES,
        directFunds: Integration.YES,
        refundPolicy: Integration.YES,
        accountSync: Integration.YES,
        refundManagement: Integration.YES,
        disputeManagement: Integration.YES,
        creditFallback: Integration.YES,
        smartDetection: Integration.YES_PAID,
        easyProfileSelector: Integration.YES,
        billingDataAutofill: Integration.YES,
        officialPartnerships: Integration.YES,
        checkoutVariables: Integration.YES_PAID,
        signedVariables: Integration.YES_PAID,
        nativePerkLists: Integration.YES,
        googleAnalytics: Integration.YES,
        detailedAnalytics: Integration.YES,
        spendingHabits: Integration.YES,
    },
    hosting: {
        bringYourInfrastructure: Integration.YES,
        dataMigration: Integration.YES,
        hourlyBasedBilling: Integration.YES,
        autoscaling: Integration.YES,
        routingRules: Integration.YES,
        justYourGame: Integration.YES,
        dedicatedPricing: 4.99,
        hardwareInformation: Integration.YES,
        softwareInformation: Integration.YES,
        geoRelay: Integration.YES_PAID,
        eventHistory: Integration.YES,
        exceptionGrouping: Integration.YES_PAID,
        detailedAnalytics: Integration.YES,
    },
    website: {
        secureTraffic: Integration.YES,
        advancedIdentity: Integration.YES,
        sessionProvider: Integration.YES,
        customizableLayout: Integration.YES_PAID,
        customizableStyle: Integration.YES,
        elements: Integration.YES,
        embedding: Integration.YES,
        adFree: Integration.YES,
        detailedAnalytics: Integration.YES,
        googleAnalytics: Integration.YES,
    },
    community: {
        newsletter: Integration.YES_PAID,
        votingSitePerformance: Integration.YES,
        votingSiteEngagement: Integration.YES_PAID,
        growthAnalytics: Integration.YES,
        peakPlayersLog: Integration.YES,
        playtimeAnalytics: Integration.YES,
        gameStats: Integration.PLANNED,
        playtimeHabits: Integration.YES_PAID,
        playerRelationshipAnalytics: Integration.YES_PAID,
        trendNotifications: Integration.YES,
        bounceAnalytics: Integration.YES,
        engagementSurveys: Integration.YES_PAID,
        leaderDetection: Integration.YES_PAID,
        googleAnalytics: Integration.YES,
        staffMembers: Integration.YES_PAID,
        geolocationAnalytics: Integration.YES,
    }
}